### PR TITLE
Adds foodcritic plugin

### PR DESCRIPTION
**Pull request by logankoester**
Foodcritic is a helpful lint tool you can use to check your Chef cookbooks for common problems. I have written a Strider plugin for it, which you can read more about at https://github.com/logankoester/strider-foodcritic.

If this is not the correct way to submit a plugin to the ecosystem, please point me in the right direction :-)

### CODE REVIEW

**Comment by keyvanfatehi** [comment]
LGTM. thank you!

**Comment by keyvanfatehi** [comment]
@logankoester please note that currently the system looks for a tag with the exact value you put in the yaml entry here. you have put 1.0.1 so the system looks for a tag 1.0.1 in https://github.com/logankoester/strider-foodcritic/releases but there is only v1.0.1. we currently do not put in the "v" or deal with that in any way. currently you must tag exactly like you do in the yaml tag entry, so your tag should be 1.0.1, not v1.0.1

**Comment by keyvanfatehi** [comment]
Please see https://github.com/Strider-CD/ecosystem-index#tagging (just updated to make it more obvious)

**Comment by logankoester** [comment]
Thanks @keyvanfatehi, I have tagged `1.0.1` now.

**Pull request merged**
